services:

  sqlserver:
    build: .
    container_name: sqlserver-lab

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: "Express"

    ports:
      - "1433:1433"

    volumes:
      - ./db:/db

    command: >
      bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 10 && 
      /db/init-db.sh &&
      wait
      "